import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { ErrorBoundary } from "next/dist/client/components/error-boundary";
import Error from "./error";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <nav className="bg-gray-800 w-screen flex content-end">
          <Link href="/" className="text-white px-5 py-3 hover:bg-gray-200 hover:text-black">
            Home
          </Link>
          <Link href="/posts" className="text-white px-5 py-3 hover:bg-gray-200 hover:text-black">
            Post
          </Link>
        </nav>
        <ErrorBoundary fallback={<Error />}>
          {children}
        </ErrorBoundary>
      </body>
    </html>
  );
}
